### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by Znarkus** [Hexagon/node-telldus#63]
Hi! Any ideas how to get this working on OS X? :)

There is no "Developer files" check during the install and Visual C++ is Windows only, as far as I know. 

I'm getting this error on npm install

```
  SOLINK_MODULE(target) Release/telldus.node
ld: framework not found TelldusCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/telldus.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/markus/www/homie/node_modules/telldus
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! telldus@0.0.9 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the telldus@0.0.9 install script.
npm ERR! This is most likely a problem with the telldus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls telldus
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/markus/www/homie
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/markus/www/homie/npm-debug.log
npm ERR! not ok code 0

```

**Comment by martingit** [comment]
I get this too. 
OS X El Capitan
TelldusCenter 2.1.2
node 0.12.5
node-gyp 2.0.1
npm 2.11.2

/Library/Frameworks/TelldusCore.framework/ contains Headers, Resources and TelldusCore (which are linked to specific version)

**Comment by Hexagon** [comment]
I don't own any apple machines (and have very little experience with those), so i cannot help you  with this. 

It shouldn't be impossible to get it working though, we just need help from someone with the right skills :)

**Comment by Hexagon** [comment]
The problem is most certainly in binding.gyp

**Comment by martingit** [comment]
the only thing it needs is to add the name of the library on the libraries line.
`'libraries': [
                '/Library/Frameworks/TelldusCore.framework/telldusCore'
            ]`

As it is now it only defines the folder, but not the library it self. I've tested it and it works.

**Comment by Hexagon** [comment]
Awesome, will fix that tonight. Thanks!

**Comment by martingit** [comment]
It's me who should thank. Great module!
