### ISSUE TITLE
Is the deviceID really working on addSensorEventListener?

### ISSUE THREAD

**Issue by jdagerot** [Hexagon/node-telldus#69]
_UPDATE: My bad. I had to restart (removing batteries) for the new channel to kick in. Sorry for disturbing, please close/delete/vaporise/nuke this issue._ 

I'm not sure this is an issue, but I don't know other channels where this can be discussed.

Unfortunately I only have two sensors right now. However when an sensorEvent is triggered (using addSensorEventListener) they both identify themselfes with deviceID 135. I have tried changing channel on the sensor but there was no difference.

**Comment by Hexagon** [comment]
No problem :)
