### ISSUE TITLE
No really an issue, but a question of best practice

### ISSUE THREAD

**Issue by jdagerot** [Hexagon/node-telldus#72]
I use 
    telldus.addDeviceEventListener

to listen on my switches. When for example switch 10 gets triggered I want to turn on three devices. However, for every device I turn on the addDeviceListener is triggered again. Why is this happening, is the device sending it's status to tellstick when the status has changed, or is tellstick triggering itself?

**Comment by Arkkimaagi** [comment]
What I understand, yes, Tellstick is triggering itself.

**Comment by plastbox** [comment]
To be fair, changing the state of a device is a "device event", regardless of it's source. Imagine an application where several distinct modules all track device state by use of addDeviceEventListener.
