### ISSUE TITLE
Generates warning on npm install

### ISSUE THREAD

**Issue by jsve** [Hexagon/node-telldus#77]
I get this warning message: 

  CXX(target) Release/obj.target/telldus/telldus.o
../telldus.cc:757:14: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
    TryCatch try_catch;
             ^
/Users/***/.node-gyp/7.0.0/include/node/v8.h:7015:40: note: 'TryCatch' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch())

where *** is really something else.

Not sure what to replace this with, however.

**Comment by Hexagon** [comment]
Fixed!
